title: 'UCSF Wynton HPC Cluster'
theme: jekyll-theme-minimal

organization:
  name: "Wynton"
  url: "https://wynton.ucsf.edu/"

user:
  name: "alice"
  email: "alice.aliceson@ucsf.edu"
  home: "/wynton/home/boblab/alice"
  labfolder: "/wynton/group/boblab"
  
cluster:
  name: "Wynton HPC"
  nickname: "Wynton"
  version: "1.0"
  email_support: support@wynton.ucsf.edu
  email_storage: storage@wynton.ucsf.edu
  email_compute: compute@wynton.ucsf.edu
  status:
    level: danger
    condition: is non-operational
    message: Complete outage due to scheduled maintenance during February 28-March 2, 2022

#   NOTE: To display the 'broadcast' icon in the navbar, edit assets/css/broadcast.css
#
#    level: info
#    condition: si perational

#    level: danger
#    condition: experiences significant issues
#    message: The system is inaccessible

#    level: warn
#    condition: experiences file-transfer issues
#    message: File transfers via Globus does not work due to issues with data-transfer node dt1.wynton.ucsf.edu

#    level: warn
#    condition: is operational but recovering
#    message: Parts of the compute nodes are being rebooted

#    level: warn
#    condition: runs at lower capacity
#    message: Fewer compute slots are available due to kernel upgrades

#    level: warn
#    condition: experiences partial problems
#    message: 

#    level: warn
#    condition: is operational
#    message: The cluster will be shut down for maintenance between February 28 and March 2, 2022. Starting February 14, the maximum job runtime will be decreased on a daily basis from the current 14 days so that jobs finish in time.

path:
  global_scratch: /wynton/scratch
  cbi_software: /wynton/home/cbi/shared/software
  
login:
  name: "log1"
  hostname: "log1.wynton.ucsf.edu"
  ip: "169.230.126.77"
devel:
  name: "dev2"
  hostname: "dev2"
  ip: "172.26.32.7"
transfer:
  name: "dt2"
  hostname: "dt2.wynton.ucsf.edu"
  ip: "169.230.126.58"

login1:
  name: "log1"
  hostname: "log1.wynton.ucsf.edu"
  ip: "169.230.126.77"
login2:
  name: "log2"
  hostname: "log2.wynton.ucsf.edu"
  ip: "169.230.134.15"
dev1:
  name: "dev1"
  hostname: "dev1"
  ip: "172.26.32.2"
dev2:
  name: "dev2"
  hostname: "dev2"
  ip: "172.26.32.7"
dev3:
  name: "dev3"
  hostname: "dev3"
  ip: "172.26.32.8"
gpudev1:
  name: "gpudev1"
  hostname: "gpudev1"
  ip: "172.26.32.3"
transfer1:
  name: "dt1"
  hostname: "dt1.wynton.ucsf.edu"
  ip: "169.230.126.58"
transfer2:
  name: "dt2"
  hostname: "dt2.wynton.ucsf.edu"
  ip: "172.26.1.17"

globus:
  name: "UCSF Wynton HPC"
  uuid: 1dd9beaa-14b7-11eb-abe2-0213fe609573

assets:
  status_root_path: "https://raw.githubusercontent.com/UCSF-HPC/wynton-slash/master/wynton/docs"

plugins:
  - jekyll-target-blank

docsearch:
  api_key: c91e1057e3e3989f56b0b30ba5ea8a0b
  index_name: hpc

google_analytics: UA-128646955-1
