on: [push, pull_request]

name: MarkdownLint

jobs:
  MarkdownLint:
    if: "! contains(github.event.head_commit.message, '[ci skip]')"

    runs-on: ubuntu-latest

    steps:
      - name: Checkout git repository
        uses: actions/checkout@v2

      - name: markdownlint-cli
        uses: nosborn/github-action-markdown-cli@v3.0.1
        with:
          files: .
          config_file: docs/.markdownlint.json
        