on: [push, pull_request]

name: MarkdownLint

jobs:
  check:
    if: "! contains(github.event.head_commit.message, '[ci skip]')"

    name: MarkdownLint

    runs-on: ubuntu-18.04

    steps:
      - name: Checkout git repository
        uses: actions/checkout@v2

      - name: markdownlint-cli
        uses: nosborn/github-action-markdown-cli@v1.1.1
        with:
          files: .
          config_file: docs/.markdownlint.json
        