on: [push, pull_request]

name: Markin_ShellCheck

jobs:
  Markin_ShellCheck:
    if: "! contains(github.event.head_commit.message, '[ci skip]')"

    runs-on: ubuntu-latest

    steps:
    - name: Checkout git repository
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        sudo apt-get install -y shellcheck
        shellcheck --version

    - name: ShellCheck
      run: |
        make markin-shellcheck
