on: [push, pull_request]

name: ShellCheck

jobs:
  ShellCheck:
    runs-on: ubuntu-18.04
    name: ShellCheck
    if: "! contains(github.event.head_commit.message, '[ci skip]')"

    steps:
    - name: Checkout git repository
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        sudo apt-get install -y shellcheck
        shellcheck --version

    - name: ShellCheck
      run: |
        make shellcheck

