on: [push, pull_request]

name: 'YAML check'

jobs:
  yaml:
    runs-on: ${{ matrix.config.os }}
    name: ${{ matrix.config.os }} (${{ matrix.config.r }})
    if: "! contains(github.event.head_commit.message, '[ci skip]')"

    strategy:
      fail-fast: false
      matrix:
        config:
          - { os: ubuntu-18.04, r: '4.0', cran: "https://demo.rstudiopm.com/all/__linux__/xenial/latest"}

    env:
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
      CRAN: ${{ matrix.config.cran }}
      
    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-r@master
        with:
          r-version: ${{ matrix.config.r }}

      - name: Install R package 'remotes'
        run: |
          install.packages("remotes")
        shell: Rscript {0}

      - name: Cache R packages
        uses: actions/cache@v1
        with:
          path: ${{ env.R_LIBS_USER }}
          key: ${{ runner.os }}-r-${{ matrix.config.r }}-yaml
          restore-keys: ${{ runner.os }}-r-${{ matrix.config.r }}-

      - name: Install R packages
        run: |
          remotes::install_cran("yaml")
        shell: Rscript {0}

      - name: Validate YAML files
        run: |
          make yaml-check
